spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debug
    username: yeang
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}